CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    employee_number VARCHAR(50) NOT NULL UNIQUE,
    swp_skill ENUM('NONE', 'FOERDERBAND', 'TREPPE', 'HT') NOT NULL DEFAULT 'NONE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shifts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    owner_id INT UNSIGNED NOT NULL,
    claimer_id INT UNSIGNED NULL,
    shift_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    provider ENUM('SWP', 'DNATA') NOT NULL,
    required_skill ENUM('NONE', 'FOERDERBAND', 'TREPPE', 'HT') NOT NULL,
    status ENUM('OPEN', 'CLAIMED') NOT NULL DEFAULT 'OPEN',
    claimed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shift_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_shift_claimer FOREIGN KEY (claimer_id) REFERENCES users(id) ON DELETE SET NULL
);
